### ISSUE TITLE
没跑起来

### ISSUE THREAD

**Issue by shijianmei** [HarmonyOS-Next/interview-handbook-project#11]

**Comment by helloworkcupid** [comment]
我也是，报错了
Sync failed. Follow the given solution to avoid unexpected errors.
Cause: The @ohos/hvigor-ohos-plugin version () is not within the expected range 2.x.x (2.x.x >= 2.4.0). Solution: Switch to @ohos/hvigor-ohos-plugin 2.4.2(which will install @ohos/hvigor 2.4.2) and import the project again.

**Comment by zhousg** [comment]
我更新下哈
