### ISSUE TITLE
现在编辑器对class没有初始化值会报错，是否改成interface

### ISSUE THREAD

**Issue by klren0312** [HarmonyOS-Next/interview-handbook-project#13]
### 文档截图
![image](https://github.com/HarmonyOS-Next/interview-handbook-project/assets/10903843/de3f30fc-3557-4b5e-9600-1b34146f6bba)

### 编辑器截图
![image](https://github.com/HarmonyOS-Next/interview-handbook-project/assets/10903843/efeb57e9-1a70-4e72-806e-119306feff60)

**Comment by zhousg** [comment]
这个是鸿蒙4.0的学习文档哈，现在的编辑器已经更新了，不建议看了，如果要开发4.0的应用，建议下载3.2版本的编辑器

**Comment by klren0312** [comment]
哦哦 收到
