### ISSUE TITLE
hvigor ERROR: 

### ISSUE THREAD

**Issue by LiJingBiao** [HarmonyOS-Next/interview-handbook-project#14]
M1Pro报错：
> hvigor ERROR: Failed :phone:default@SignHap... 
> hvigor ERROR: Invalid storeFile value. Make sure it is not null or empty. The file must be included in '/Users/zhousg/.ohos/config/default_interview-handbook-project_HLKK-jbFP2i_86C1kdyuRrPB-WXQXKhyYK6HPBpJVIo=.p12'.
	 Detail: Please check signingConfigs in root project build-profile.json5
	 at /Users/xxxxxx/Desktop/interview-handbook-project-next/build-profile.json5
> hvigor ERROR: BUILD FAILED in 220 ms 
<img width="991" alt="image" src="https://github.com/HarmonyOS-Next/interview-handbook-project/assets/5698458/914dc045-5658-4d52-a791-9abc6f6793ba">

**Comment by zhousg** [comment]
自己生成下证书哈
