### ISSUE TITLE
跟随系统无效

### ISSUE THREAD

**Issue by geeklx** [HarmonyOS-Next/interview-handbook-project#15]
点击我的-深色模式-跟随系统，没反应，重启无效

**Comment by zhousg** [comment]
刚看了下  this.app.setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET) 在API12好像无效，设置完成之后值还是 ConfigurationConstant.ColorMode.COLOR_MODE_LIGHT

**Comment by zhousg** [comment]
fix https://github.com/HarmonyOS-Next/interview-handbook-project/commit/f5c7ab1fc00e42eaa53c12fa478759b9c2aed3a7  API12修复了主题颜色的BUG  不用重启，改了下实现方式

**Comment by geeklx** [comment]
牛逼
