### ISSUE TITLE
macOS m1用next分支进行preview失败

### ISSUE THREAD

**Issue by starlight-tech-studio** [HarmonyOS-Next/interview-handbook-project#16]
用的是api 11，失败图片如下
<img width="416" alt="截屏2024-07-10 13 39 09" src="https://github.com/HarmonyOS-Next/interview-handbook-project/assets/34531056/992af4c6-855a-43b4-acb1-51ffb61e053e">

**Comment by zhousg** [comment]
有些能力试无法用预览器的，静态页面可以，建议用模拟器运行

**Comment by starlight-tech-studio** [comment]
使用模拟器可以正常运行，非常感谢。
