### ISSUE TITLE
Cannot find module '@itcast/mine' or its corresponding type declarations.

### ISSUE THREAD

**Issue by YeaLink89** [HarmonyOS-Next/interview-handbook-project#18]
大佬是不是  itcast这个模块没有上传，这个目录下的模块都找不到。

**Comment by zhousg** [comment]
这个是本地模块，同步下依赖试试
<img width="896" alt="image" src="https://github.com/user-attachments/assets/fca041e9-bdf5-4253-81aa-0b9811a3d012">
