### ISSUE TITLE
拉下来后运行就报这个

### ISSUE THREAD

**Issue by yanghaidong02** [HarmonyOS-Next/interview-handbook-project#20]
博主，你好，请问一下这种应该怎么处理呀？
![微信图片_20240725120014](https://github.com/user-attachments/assets/bf7f5313-5974-483e-96e6-035082a2f020)

**Comment by zhousg** [comment]
**先用模拟器跑吧，** 预览器更新后语法严格了，我待会修复下，你更新下就可以预览
