### ISSUE TITLE
请问一下，如下图所示，模拟器的分辨率是1260px，密度是520，那是不是针对这个模拟器而言，整个宽度就是(1260/520 * 160) = 387.69vp？如果我UI图一比一开发的话，是不是将UI图的宽度改为387.69就行了？感谢各位大佬的解释

### ISSUE THREAD

**Issue by shaolong1314** [HarmonyOS-Next/interview-handbook-project#24]
![微信截图_20241024180359](https://github.com/user-attachments/assets/6eab0902-ab4f-4c36-86cc-b14dcde08e17)

**Comment by zhousg** [comment]
一般是360倍数的设计稿

**Comment by shaolong1314** [comment]
> 一般是360倍数的设计稿

好的，您这个项目的设计稿设计宽度是360吗？如果用720设计稿，无法一比一开发吧

**Comment by zhousg** [comment]
不同设备宽度不一样，所以不可能所有1比1

我用的750的，看你怎么适配，是仅仅宽度适配，还是等比例适配

还有一个单位 lpx 可以了解下
