### ISSUE TITLE
next分之为什么放弃了 navigation

### ISSUE THREAD

**Issue by hutaoao** [HarmonyOS-Next/interview-handbook-project#26]

**Comment by zhousg** [comment]
4.0的时候只是把 navigation 当容器使用了布局自定义不好，next就去掉了

**Comment by zhousg** [comment]
而且这个项目使用的事 router 模式的路由，未采用 navigation 路由

**Comment by hutaoao** [comment]
大佬，next分之相对master业务拆分比较大啊（看下图），对于我们新手 master业务架构能看懂，next就有点吃力。能不能空的时候文档上补充说明下，我们这些鸿蒙小白会十分感谢的🙏
![1731032676200](https://github.com/user-attachments/assets/495f2a9a-f9d8-479d-9296-212675a3a7a1)

**Comment by zhousg** [comment]
products  产品入口，是hap包
-- phone   
features  需求模块
-- home
-- project
-- interview
-- mine
commons 通用层
-- basic
-- calendar
