### ISSUE TITLE
面试录音好像无法正常使用

### ISSUE THREAD

**Issue by ChunYunMuXue** [HarmonyOS-Next/interview-handbook-project#29]

**Comment by zhousg** [comment]
这个是基础版本，有些功能代码没上传。 可以参考 https://gitee.com/zhoushugang/interview_success/blob/main/entry/src/main/ets/pages/AudioPage.ets

**Comment by ChunYunMuXue** [comment]
噢好的 感谢您

**Comment by ChunYunMuXue** [comment]
但是我这里还有一个问题就是gitee的版本我本地部署的时候发现无法点开收藏 历史记录 以及点赞

**Comment by zhousg** [comment]
收藏 历史记录 以及点赞  都比较基础的功能，可以相互参考下

**Comment by ChunYunMuXue** [comment]
您好我想请问您是否有最终完整项目呢

**Comment by ChunYunMuXue** [comment]
我可以有偿希望能够参考一下
