### ISSUE TITLE
工程下载下来run到模拟器上出现问题

### ISSUE THREAD

**Issue by weilei131** [HarmonyOS-Next/interview-handbook-project#6]
IDE环境：
DevEco Studio 3.1.1 Release
Build Version: 3.1.0.501, built on June 20, 2023
Build #DS-223.8617.56.36.310501
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
node：v21.3.0

下载下来后run就出现如下问题：
D:\ProgramFiles\Huawei\SDK\nodejs\node.exe C:\Users\username\.hvigor\project_caches\2eafdc46c1d877dae5fe2e7cac2d2557\workspace\node_modules\@ohos\hvigor\bin\hvigor.js --mode module -p module=phone@default -p product=default -p debuggable=true assembleHap
> hvigor ERROR: Task assembleHap not found in hvigor node: phone.
> hvigor ERROR: BUILD FAILED in 36 ms 

请问是我的编译器有问题吗？

**Comment by zhousg** [comment]
3.1 编辑器，切换到了main分支运行吗？

**Comment by weilei131** [comment]
> 3.1 编辑器，切换到了main分支运行吗？

我按照你的方法，切换到main分支就可以正常运行了。
谢谢。

**Comment by o0o0oo00** [comment]
运行不起来可以把根目录下 build-profile.json5 signingConfigs置空 "signingConfigs": []
